# Mapping of cryptocurrency names to their service class names
WALLET_SERVICES = {
    "Binance Coin": "binance_coin",
    "Bitcoin": "bitcoin",
    "Bitcoin Cash": "btc_cash",
    "Bitcoin Gold": "btc_gold",
    "Cardano": "cardano",
    "Cosmos": "cosmos",
    "Diamond Coin": "dmd",
    "Dogecoin": "dogecoin",
    "Ethereum": "ethereum",
    "Ethereum Classic": "ethereum_classic",
    "Helium": "helium",
    "IOTA": "iota",
    "Litecoin": "litecoin",
    "Monero": "monero",
    "OKCash": "okcash",
    "Ripple": "ripple",
    "Tether": "tether",
    "Shiba Inu": "shiba",
    "Zcash": "zcash",
}